In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("dulieuxettuyendaihoc.csv")
data.head(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

In [15]:
X = data[len(data) - 10: ]
X = pd.DataFrame(X)
X.head(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

In [14]:
data.tail(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

In [5]:
data.fillna(0, inplace = True)
data.tail(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,8.3,8.7,7.8,M,0.0,2,6.25,4.00,6.50,A
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,7.2,7.4,7.0,M,0.0,2NT,4.75,4.75,4.50,A
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,5.9,6.7,5.8,M,0.0,1,3.25,5.25,4.25,A
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,8.7,7.8,5.0,M,0.0,1,3.50,4.25,5.00,A
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,7.3,6.8,5.3,M,0.0,1,4.25,2.50,4.75,A
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [6]:
data["T1"].fillna(data["T1"].mean(), inplace = False)

0     7.2
1     5.4
2     5.6
3     6.6
4     6.0
     ...
95    8.6
96    3.7
97    8.8
98    2.7
99    4.1
Name: T1, Length: 100, dtype: float64

In [7]:
def fillData(data, col): 
    return data[col].fillna(data[col].mean(), inplace = False)

for col in data.columns:
    datatype = str(data[col].dtype)
    if datatype in ["float64", "int64"]:
        fillData(data, col)

In [8]:
'''
TBM = (T*2 + L + H + S + V*2 + X + D + N) / 10
'''
for i in ["1", "2", "3"]:
    data["TBM" + i] = np.round(((data["T" + i] * 2) + data["L" + i] + data["H" + i] + data["S" + i] + (data["V" + i] * 2) + data['X' + i] + data['D' + i] + data['N' + i]) / 10, 2)

In [29]:
data.head(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,3.25,3.25,4.50,A1,7.00,7.54,7.06,K,K,K
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.00,4.00,3.50,C,4.69,5.47,4.70,Y,TB,Y
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.00,6.75,4.00,C,5.77,5.38,4.33,TB,TB,Y
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,4.25,4.25,5.25,D1,6.21,5.20,6.03,TB,TB,TB
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,4.25,4.50,5.00,A,6.50,6.36,7.01,K,TB,K
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,1.50,4.00,6.00,D1,7.96,8.54,7.82,K,G,K
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.50,6.75,5.25,C,4.90,5.60,5.24,Y,TB,TB
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,3.75,4.50,4.25,D1,6.80,6.87,6.95,K,K,K
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,3.50,3.50,6.75,D1,6.23,6.72,6.59,TB,K,K
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,4.00,4.75,5.50,D1,6.80,7.25,7.12,K,K,K

# Bai 8

In [27]:
def evaluate(score):
    if score < 5.0: return "Y"
    elif 5.0 <= score < 6.5: return "TB"
    elif 6.5 <= score < 8.0: return "K"
    elif 8.0 <= score < 9.0: return "G"
    return "XS"

for i in ["1", "2", "3"]:
    col_name = data["TBM" + i].values
    tmp = []
    for col in col_name: tmp.append(evaluate(col))
    data["XL" + i] = tmp

In [28]:
data.head(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,3.25,3.25,4.50,A1,7.00,7.54,7.06,K,K,K
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.00,4.00,3.50,C,4.69,5.47,4.70,Y,TB,Y
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,5.00,6.75,4.00,C,5.77,5.38,4.33,TB,TB,Y
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,4.25,4.25,5.25,D1,6.21,5.20,6.03,TB,TB,TB
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,4.25,4.50,5.00,A,6.50,6.36,7.01,K,TB,K
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,1.50,4.00,6.00,D1,7.96,8.54,7.82,K,G,K
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.50,6.75,5.25,C,4.90,5.60,5.24,Y,TB,TB
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,3.75,4.50,4.25,D1,6.80,6.87,6.95,K,K,K
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,3.50,3.50,6.75,D1,6.23,6.72,6.59,TB,K,K
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,4.00,4.75,5.50,D1,6.80,7.25,7.12,K,K,K

# Bai 9
# Normalization score by using Min Max Normalization

In [43]:
def minMaxScaler(val_fl):
    return (val_fl * 4) / 10


for i in ["1", "2", "3"]:
    col_name = data[f"TBM{i}"]
    np_arr = np.array(col_name)
    data[f"US_TBM{i}"] = minMaxScaler(np_arr)

In [44]:
data.head(10)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,A1,7.00,7.54,7.06,K,K,K,2.800,3.016,2.824
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,C,4.69,5.47,4.70,Y,TB,Y,1.876,2.188,1.880
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,C,5.77,5.38,4.33,TB,TB,Y,2.308,2.152,1.732
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,D1,6.21,5.20,6.03,TB,TB,TB,2.484,2.080,2.412
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,A,6.50,6.36,7.01,K,TB,K,2.600,2.544,2.804
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,D1,7.96,8.54,7.82,K,G,K,3.184,3.416,3.128
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,C,4.90,5.60,5.24,Y,TB,TB,1.960,2.240,2.096
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,D1,6.80,6.87,6.95,K,K,K,2.720,2.748,2.780
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,D1,6.23,6.72,6.59,TB,K,K,2.492,2.688,2.636
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,D1,6.80,7.25,7.12,K,K,K,2.720,2.900,2.848

# Bai 10

In [55]:
'''
A = (DH1 * 2 + DH2 + DH3) / 4
B = (DH1 + DH2 * 2 + DH3) / 4
C = (DH1 + DH2 + DH3) / 3
'''
def transform(data, col):
    data[col] = data[col].map({True: "1", False: "0"})

dh1 = data["DH1"]
dh2 = data["DH2"]
dh3 = data["DH3"]

data["A"] = (dh1 * 2 + dh2 + dh3) / 4
data["B"] = (dh1 + dh2 * 2 + dh3) / 4
data["K"] = (dh1 + dh2 + dh3) / 3
data["A"] = data["A"] >= 5.0
data["B"] = data["B"] >= 5.0
data["K"] = data["K"] >= 5.0
transform(data, "A")
transform(data, "B")
transform(data, "K")

In [58]:
data.head(30)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,TBM3,XL1,XL2,XL3,US_TBM1,US_TBM2,US_TBM3,A,B,K
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,7.06,K,K,K,2.800,3.016,2.824,0,0,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,4.70,Y,TB,Y,1.876,2.188,1.880,0,0,0
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,4.33,TB,TB,Y,2.308,2.152,1.732,1,1,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,6.03,TB,TB,TB,2.484,2.080,2.412,0,0,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,7.01,K,TB,K,2.600,2.544,2.804,0,0,0
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,7.82,K,G,K,3.184,3.416,3.128,0,0,0
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,5.24,Y,TB,TB,1.960,2.240,2.096,1,1,1
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,6.95,K,K,K,2.720,2.748,2.780,0,0,0
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,6.59,TB,K,K,2.492,2.688,2.636,0,0,0
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,7.12,K,K,K,2.720,2.900,2.848,0,0,0
10,11,5.2,6.4,7.4,7.0,7.1,8.1,7.6,6.8,6.3,...,7.65,K,K,K,2.716,2.912,3.060,0,0,0
11,12,7.9,7.0,9.1,8.6,6.1,7.0,5.6,9.0,8.2,...,7.49,K,K,K,2.972,3.088,2.996,1,1,1
12,13,7.3,6.3,8.7,7.7,6.6,8.5,6.9,8.5,5.8,...,7.86,K,K,K,2.976,2.728,3.144,0,0,0
13,14,4.9,5.4,5.0,5.0,5.8,7.0,4.2,5.8,4.5,...,5.69,TB,TB,TB,2.152,2.204,2.276,0,0,0
14,15,7.1,8.0,9.1,7.5,6.1,7.7,7.9,7.6,8.3,...,7.49,K,K,K,2.968,3.028,2.996,0,0,0
15,16,2.5,5.3,4.9,8.2,6.9,6.0,6.7,5.0,6.2,...,6.39,TB,TB,TB,2.196,2.576,2.556,0,0,0
16,17,8.8,7.0,7.7,7.1,6.1,5.4,8.3,5.3,7.3,...,6.99,K,K,K,2.824,2.756,2.796,0,0,0
17,18,5.4,6.0,4.9,5.5,4.2,7.3,5.3,4.9,4.8,...,6.71,TB,TB,K,2.124,2.464,2.684,0,0,0
18,19,5.6,4.8,7.3,3.9,5.5,6.0,6.1,4.8,5.5,...,6.26,TB,TB,TB,2.204,2.260,2.504,0,0,0
19,20,8.2,7.3,7.8,7.6,5.6,7.2,6.0,6.5,6.4,...,6.42,K,TB,TB,2.800,2.488,2.568,0,0,0
20,21,3.9,3.9,6.0,6.7,6.1,4.8,6.3,5.2,5.6,...,6.35,TB,TB,TB,2.116,2.372,2.540,0,0,0
21,22,5.0,5.1,6.3,4.5,6.8,5.8,5.1,4.1,5.8,...,5.98,TB,TB,TB,2.180,2.084,2.392,0,0,0
22,23,5.0,4.5,5.3,6.8,4.8,5.5,5.5,5.5,5.5,...,5.53,TB,TB,TB,2.108,2.332,2.212,0,0,0
23,24,5.3,6.3,5.7,6.9,5.9,7.5,6.6,5.1,6.4,...,6.20,TB,TB,TB,2.420,2.528,2.480,1,1,1
24,25,2.4,4.1,3.6,5.5,5.9,5.6,4.9,4.2,3.3,...,5.31,Y,Y,TB,1.780,1.952,2.124,1,0,0
25,26,3.6,5.8,6.9,6.1,5.5,7.2,5.5,4.3,4.2,...,5.02,TB,TB,TB,2.160,2.080,2.008,0,0,0
26,27,4.9,4.8,5.0,5.4,5.2,5.3,6.5,4.4,5.9,...,5.81,TB,TB,TB,2.064,2.188,2.324,0,0,0
27,28,8.1,5.5,5.1,5.6,6.2,6.2,6.6,4.8,4.4,...,5.32,TB,TB,TB,2.496,2.200,2.128,0,0,0
28,29,6.3,6.4,6.6,6.7,6.6,8.1,7.8,4.5,8.1,...,5.74,K,TB,TB,2.636,2.412,2.296,0,0,0
29,30,4.5,3.8,4.8,5.9,4.3,6.2,5.2,6.1,5.5,...,6.00,Y,TB,TB,1.984,2.208,2.400,0,0,0

# Bai 11: Save file csv

In [59]:
data.to_csv("processed_dulieuxettuyendaihoc.csv")